import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { branches, products, statusFor, stockFor, displayName } from "@/lib/estock-data";
import { useColors } from "@/hooks/use-colors";

export default function المخزونScreen() {
  const colors = useColors(); const [query, setQuery] = useState(""); const [branchId, setBranchId] = useState(1); const [filter, setFilter] = useState("الكل");
  const list = useMemo(() => products.filter((p) => { const q = query.toLowerCase(); const matches = !q || [p.englishName, p.composition, p.barcode, p.sku].some((v) => v.toLowerCase().includes(q)); const status = statusFor(p, branchId); return matches && (filter === "الكل" || (filter === "تحتاج متابعة" ? ["low", "out", "expiring"].includes(status) : status === filter.toLowerCase())); }), [query, branchId, filter]);
  const badge = (status: string) => ({ healthy: ["متوفر", colors.success], low: ["مخزون منخفض", colors.warning], expiring: ["قارب على الانتهاء", colors.warning], out: ["نافد", colors.error] } as Record<string, string[]>)[status];
  return <ScreenContainer className="px-5" containerClassName="bg-background"><View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.success }]}>دليل الأصناف</Text><Text style={[styles.title, { color: colors.foreground }]}>المخزون</Text></View><Pressable onPress={() => router.push("/operations" as never)} style={[styles.roundButton, { backgroundColor: colors.primary }]}><IconSymbol name="plus" size={22} color="#fff" /></Pressable></View><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="magnifyingglass" size={20} color={colors.muted} /><TextInput placeholder="ابحث بالاسم أو التركيب أو الباركود" placeholderTextColor={colors.muted} value={query} onChangeText={setQuery} style={[styles.input, { color: colors.foreground }]} /></View><View style={styles.chips}>{branches.map((b) => <Pressable key={b.id} onPress={() => setBranchId(b.id)} style={[styles.chip, { borderColor: branchId === b.id ? colors.primary : colors.border, backgroundColor: branchId === b.id ? colors.primary : colors.surface }]}><Text style={{ color: branchId === b.id ? "#fff" : colors.muted, fontWeight: "700", fontSize: 12 }}>{b.name}</Text></Pressable>)}</View><View style={styles.chips}>{["الكل", "تحتاج متابعة", "متوفرة"].map((f) => <Pressable key={f} onPress={() => setFilter(f)} style={[styles.filter, { backgroundColor: filter === f ? "#DDF4EE" : "transparent" }]}><Text style={{ color: filter === f ? colors.primary : colors.muted, fontWeight: "700", fontSize: 12 }}>{f}</Text></Pressable>)}</View><Text style={[styles.count, { color: colors.muted }]}>{list.length} صنف في القائمة</Text><FlatList data={list} keyExtractor={(item) => String(item.id)} contentContainerStyle={{ paddingBottom: 24, gap: 10 }} renderItem={({ item }) => { const stock = stockFor(item, branchId); const [label, tone] = badge(statusFor(item, branchId)); return <Pressable onPress={() => router.push(`/product/${item.id}` as never)} style={({ pressed }) => [styles.card, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && { opacity: 0.72 }]}><View style={styles.cardTop}><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground }]} numberOfLines={1}>{displayName(item)}</Text><Text style={[styles.meta, { color: colors.muted }]} numberOfLines={1}>{item.company} · {item.form}</Text></View><View style={[styles.badge, { backgroundColor: `${tone}22` }]}><View style={[styles.dot, { backgroundColor: tone }]} /><Text style={{ color: tone, fontSize: 11, fontWeight: "800" }}>{label}</Text></View></View><View style={styles.cardBottom}><Text style={[styles.composition, { color: colors.muted }]} numberOfLines={1}>{item.composition}</Text><View style={styles.stock}><Text style={[styles.qty, { color: colors.foreground }]}>{stock?.quantity ?? 0}</Text><Text style={[styles.unit, { color: colors.muted }]}> وحدة</Text></View></View></Pressable> }} /></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingTop: 20, paddingBottom: 18 }, eyebrow: { fontSize: 11, fontWeight: "800", letterSpacing: 1.4 }, title: { fontSize: 30, fontWeight: "800", marginTop: 5 }, roundButton: { width: 44, height: 44, borderRadius: 15, alignItems: "center", justifyContent: "center" }, search: { height: 52, borderWidth: 1, borderRadius: 16, flexDirection: "row", alignItems: "center", gap: 9, paddingHorizontal: 15 }, input: { flex: 1, fontSize: 13 }, chips: { flexDirection: "row", gap: 8, marginTop: 12 }, chip: { paddingHorizontal: 13, paddingVertical: 9, borderRadius: 20, borderWidth: 1 }, filter: { paddingHorizontal: 13, paddingVertical: 8, borderRadius: 14 }, count: { fontSize: 12, marginTop: 18, marginBottom: 10 }, card: { borderWidth: 1, borderRadius: 18, padding: 15 }, cardTop: { flexDirection: "row", gap: 8, alignItems: "flex-start" }, name: { fontSize: 15, fontWeight: "800" }, meta: { fontSize: 11, marginTop: 4 }, badge: { borderRadius: 10, paddingHorizontal: 8, paddingVertical: 6, flexDirection: "row", gap: 5, alignItems: "center" }, dot: { width: 6, height: 6, borderRadius: 3 }, cardBottom: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", marginTop: 15 }, composition: { flex: 1, fontSize: 11 }, stock: { flexDirection: "row", alignItems: "baseline", marginLeft: 8 }, qty: { fontSize: 20, fontWeight: "800" }, unit: { fontSize: 11 } });
